version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datacounts
    ports:
      - "3306:3306"
    volumes:
      - datacounts.sql:/datacounts.sql